config/routes.rb
Rails.application.routes.draw do
  resources :boards
  resources :users

  root 'boards#index'

  get 'posts/new', to: 'posts#new', as: 'new_post' 
  
  post 'posts' => 'posts#create' 

end

app/models/board.rb
class Board < ActiveRecord::Base
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :board
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @posts = Post.where(board_id: @board.id)
    @users = User.all
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		@post = Post.new(board_id: params[:board_id])
		#Strictly for button back to boards/:id
		@board = Board.find(params[:board_id])
	end

	def create
		@post = Post.new(post_params)
		@board = Board.find(post_params[:board_id])
		if @post.save
			#some action
			redirect_to @board
		else
			#some action
		end
	end

	private

	def set_post

	end

	def post_params
		#whitelist the parameters
		params.require(:post).permit(:user_id, :board_id, :content, :rating)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board--Brian was here!</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.name %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @board.name %> Board</h1>

<ul>
<% @posts.each do |post| %>
	<li>
		<div class="well">
			<p><%= post.content %></p>
			<p><%= post.user.name %></p>
		</p>
	</li>
<% end %>
</ul>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>
<%= form_tag(new_post_path, method: "get") do %>
	<%= hidden_field_tag(:board_id, @board.id) %>
	<%= submit_tag("Post New Comment") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= link_to 'Back to Board', @board %>
<%= form_for(@post) do |f| %>
	<%= f.label :user_id %>
	<%= f.text_field :user_id %><br/>
	<%= f.label :content %>
	<%= f.text_area :content %>
	<%= f.hidden_field :board_id, value: @post.board_id %>
	<%= f.hidden_field :rating, value: 0 %>
	<%= f.submit "Create" %>
<% end %>

<%= params[:board_id] %>